// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {adapter} from '../models';
import {bridge} from '../models';
import {context} from '../models';
import {engine} from '../models';
import {config} from '../models';
import {tool} from '../models';

export function Approve(arg1:string,arg2:boolean):Promise<void>;

export function ChooseWorkspace():Promise<string>;

export function ClearConversation():Promise<void>;

export function EmitAssistant(arg1:string):Promise<void>;

export function GetConversations():Promise<Record<string, any>>;

export function GetRules():Promise<Record<string, Array<string>>>;

export function GetSettings():Promise<Record<string, string>>;

export function GetTools():Promise<Array<Record<string, any>>>;

export function LoadConversation(arg1:string):Promise<void>;

export function NewConversation():Promise<string>;

export function PromptApproval(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function SaveRules(arg1:Record<string, Array<string>>):Promise<void>;

export function SaveSettings(arg1:Record<string, string>):Promise<void>;

export function SendChat(arg1:string,arg2:string):Promise<void>;

export function SendUserMessage(arg1:string):Promise<void>;

export function SetBusy(arg1:boolean):Promise<void>;

export function SetModel(arg1:string):Promise<void>;

export function SetWorkspace(arg1:string):Promise<void>;

export function WithConfig(arg1:adapter.Config):Promise<bridge.App>;

export function WithContext(arg1:context.Context):Promise<bridge.App>;

export function WithEngine(arg1:engine.Engine):Promise<bridge.App>;

export function WithSettings(arg1:config.Settings):Promise<bridge.App>;

export function WithTools(arg1:tool.Registry):Promise<bridge.App>;
