// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function Approve(arg1:string,arg2:boolean):Promise<void>;

export function EmitAssistant(arg1:string):Promise<void>;

export function GetTools():Promise<Array<Record<string, any>>>;

export function PromptApproval(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function SendChat(arg1:string,arg2:string):Promise<void>;

export function SendUserMessage(arg1:string):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;
