// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Approve(arg1, arg2) {
  return window['go']['bridge']['App']['Approve'](arg1, arg2);
}

export function GetTools() {
  return window['go']['bridge']['App']['GetTools']();
}

export function PromptApproval(arg1, arg2, arg3) {
  return window['go']['bridge']['App']['PromptApproval'](arg1, arg2, arg3);
}

export function SendChat(arg1, arg2) {
  return window['go']['bridge']['App']['SendChat'](arg1, arg2);
}

export function SendUserMessage(arg1) {
  return window['go']['bridge']['App']['SendUserMessage'](arg1);
}

export function SetContext(arg1) {
  return window['go']['bridge']['App']['SetContext'](arg1);
}
