// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {adapter} from '../models';
import {bridge} from '../models';
import {engine} from '../models';
import {tool} from '../models';

export function Approve(arg1:string,arg2:boolean):Promise<void>;

export function EmitAssistant(arg1:string):Promise<void>;

export function GetTools():Promise<Array<Record<string, any>>>;

export function PromptApproval(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function SendChat(arg1:string,arg2:string):Promise<void>;

export function SendUserMessage(arg1:string):Promise<void>;

export function SetModel(arg1:string):Promise<void>;

export function WithConfig(arg1:adapter.Config):Promise<bridge.App>;

export function WithEngine(arg1:engine.Engine):Promise<bridge.App>;

export function WithTools(arg1:tool.Registry):Promise<bridge.App>;
