// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function ApproveTask(arg1:string):Promise<void>;

export function ClearChat():Promise<void>;

export function GetAllTasks():Promise<Record<string, Array<models.TaskInfo>>>;

export function GetAppInfo():Promise<Record<string, any>>;

export function GetChatState():Promise<models.ChatState>;

export function GetFileAutocomplete(arg1:string):Promise<Array<string>>;

export function GetFileTree():Promise<Array<models.FileInfo>>;

export function GetPendingConfirmations():Promise<Array<models.TaskConfirmation>>;

export function GetProjectSummary():Promise<models.ProjectSummary>;

export function Greet(arg1:string):Promise<string>;

export function ReadFile(arg1:string):Promise<string>;

export function RejectTask(arg1:string):Promise<void>;

export function SearchFiles(arg1:string):Promise<Array<models.FileInfo>>;

export function SendMessage(arg1:string):Promise<void>;

export function StopStreaming():Promise<void>;
