// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApproveTask(arg1) {
  return window['go']['main']['App']['ApproveTask'](arg1);
}

export function ClearChat() {
  return window['go']['main']['App']['ClearChat']();
}

export function GetAllTasks() {
  return window['go']['main']['App']['GetAllTasks']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetChatState() {
  return window['go']['main']['App']['GetChatState']();
}

export function GetFileAutocomplete(arg1) {
  return window['go']['main']['App']['GetFileAutocomplete'](arg1);
}

export function GetFileTree() {
  return window['go']['main']['App']['GetFileTree']();
}

export function GetPendingConfirmations() {
  return window['go']['main']['App']['GetPendingConfirmations']();
}

export function GetProjectSummary() {
  return window['go']['main']['App']['GetProjectSummary']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function RejectTask(arg1) {
  return window['go']['main']['App']['RejectTask'](arg1);
}

export function SearchFiles(arg1) {
  return window['go']['main']['App']['SearchFiles'](arg1);
}

export function SelectWorkspace(arg1) {
  return window['go']['main']['App']['SelectWorkspace'](arg1);
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function StopStreaming() {
  return window['go']['main']['App']['StopStreaming']();
}
