// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Approve(arg1, arg2) {
  return window['go']['bridge']['App']['Approve'](arg1, arg2);
}

export function ChooseSaveFile(arg1) {
  return window['go']['bridge']['App']['ChooseSaveFile'](arg1);
}

export function ChooseWorkspace() {
  return window['go']['bridge']['App']['ChooseWorkspace']();
}

export function ClearConversation() {
  return window['go']['bridge']['App']['ClearConversation']();
}

export function EmitAssistant(arg1) {
  return window['go']['bridge']['App']['EmitAssistant'](arg1);
}

export function EmitBilling(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['bridge']['App']['EmitBilling'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function EmitReasoning(arg1, arg2) {
  return window['go']['bridge']['App']['EmitReasoning'](arg1, arg2);
}

export function FindFiles(arg1, arg2, arg3) {
  return window['go']['bridge']['App']['FindFiles'](arg1, arg2, arg3);
}

export function GetConversations() {
  return window['go']['bridge']['App']['GetConversations']();
}

export function GetRules() {
  return window['go']['bridge']['App']['GetRules']();
}

export function GetSettings() {
  return window['go']['bridge']['App']['GetSettings']();
}

export function GetTools() {
  return window['go']['bridge']['App']['GetTools']();
}

export function GetUsage() {
  return window['go']['bridge']['App']['GetUsage']();
}

export function ListWorkspaceDir(arg1) {
  return window['go']['bridge']['App']['ListWorkspaceDir'](arg1);
}

export function LoadConversation(arg1) {
  return window['go']['bridge']['App']['LoadConversation'](arg1);
}

export function NewConversation() {
  return window['go']['bridge']['App']['NewConversation']();
}

export function OpenFileInUI(arg1) {
  return window['go']['bridge']['App']['OpenFileInUI'](arg1);
}

export function PromptApproval(arg1, arg2, arg3) {
  return window['go']['bridge']['App']['PromptApproval'](arg1, arg2, arg3);
}

export function ReadWorkspaceFile(arg1) {
  return window['go']['bridge']['App']['ReadWorkspaceFile'](arg1);
}

export function ResetUsage() {
  return window['go']['bridge']['App']['ResetUsage']();
}

export function SaveRules(arg1) {
  return window['go']['bridge']['App']['SaveRules'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['bridge']['App']['SaveSettings'](arg1);
}

export function SearchCode(arg1, arg2, arg3) {
  return window['go']['bridge']['App']['SearchCode'](arg1, arg2, arg3);
}

export function SendChat(arg1, arg2) {
  return window['go']['bridge']['App']['SendChat'](arg1, arg2);
}

export function SendUserMessage(arg1) {
  return window['go']['bridge']['App']['SendUserMessage'](arg1);
}

export function SetBusy(arg1) {
  return window['go']['bridge']['App']['SetBusy'](arg1);
}

export function SetModel(arg1) {
  return window['go']['bridge']['App']['SetModel'](arg1);
}

export function SetWorkspace(arg1) {
  return window['go']['bridge']['App']['SetWorkspace'](arg1);
}

export function UpdateEditorContext(arg1, arg2, arg3) {
  return window['go']['bridge']['App']['UpdateEditorContext'](arg1, arg2, arg3);
}

export function WithConfig(arg1) {
  return window['go']['bridge']['App']['WithConfig'](arg1);
}

export function WithContext(arg1) {
  return window['go']['bridge']['App']['WithContext'](arg1);
}

export function WithEngine(arg1) {
  return window['go']['bridge']['App']['WithEngine'](arg1);
}

export function WithSettings(arg1) {
  return window['go']['bridge']['App']['WithSettings'](arg1);
}

export function WithTools(arg1) {
  return window['go']['bridge']['App']['WithTools'](arg1);
}

export function WriteWorkspaceFile(arg1) {
  return window['go']['bridge']['App']['WriteWorkspaceFile'](arg1);
}
