// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Approve(arg1, arg2) {
  return window['go']['bridge']['App']['Approve'](arg1, arg2);
}

export function ChooseSaveFile(arg1) {
  return window['go']['bridge']['App']['ChooseSaveFile'](arg1);
}

export function ChooseWorkspace() {
  return window['go']['bridge']['App']['ChooseWorkspace']();
}

export function ClearConversation() {
  return window['go']['bridge']['App']['ClearConversation']();
}

export function CreateNewProject(arg1) {
  return window['go']['bridge']['App']['CreateNewProject'](arg1);
}

export function DeleteMemory(arg1) {
  return window['go']['bridge']['App']['DeleteMemory'](arg1);
}

export function EmitAssistant(arg1) {
  return window['go']['bridge']['App']['EmitAssistant'](arg1);
}

export function EmitBilling(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['bridge']['App']['EmitBilling'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function EmitReasoning(arg1, arg2) {
  return window['go']['bridge']['App']['EmitReasoning'](arg1, arg2);
}

export function FindFiles(arg1, arg2, arg3) {
  return window['go']['bridge']['App']['FindFiles'](arg1, arg2, arg3);
}

export function GetConversations() {
  return window['go']['bridge']['App']['GetConversations']();
}

export function GetGlobalUsage() {
  return window['go']['bridge']['App']['GetGlobalUsage']();
}

export function GetMemories() {
  return window['go']['bridge']['App']['GetMemories']();
}

export function GetPersonalities() {
  return window['go']['bridge']['App']['GetPersonalities']();
}

export function GetProfileData(arg1, arg2) {
  return window['go']['bridge']['App']['GetProfileData'](arg1, arg2);
}

export function GetProjectHotlist() {
  return window['go']['bridge']['App']['GetProjectHotlist']();
}

export function GetProjectProfile() {
  return window['go']['bridge']['App']['GetProjectProfile']();
}

export function GetProjectRules() {
  return window['go']['bridge']['App']['GetProjectRules']();
}

export function GetRecentWorkspaces() {
  return window['go']['bridge']['App']['GetRecentWorkspaces']();
}

export function GetRules() {
  return window['go']['bridge']['App']['GetRules']();
}

export function GetSettings() {
  return window['go']['bridge']['App']['GetSettings']();
}

export function GetSymbols(arg1, arg2) {
  return window['go']['bridge']['App']['GetSymbols'](arg1, arg2);
}

export function GetSymbolsCount() {
  return window['go']['bridge']['App']['GetSymbolsCount']();
}

export function GetSymbolsDebug() {
  return window['go']['bridge']['App']['GetSymbolsDebug']();
}

export function GetTools() {
  return window['go']['bridge']['App']['GetTools']();
}

export function GetUILayout() {
  return window['go']['bridge']['App']['GetUILayout']();
}

export function GetUsage() {
  return window['go']['bridge']['App']['GetUsage']();
}

export function IndexDone(arg1) {
  return window['go']['bridge']['App']['IndexDone'](arg1);
}

export function IndexProgress(arg1, arg2, arg3) {
  return window['go']['bridge']['App']['IndexProgress'](arg1, arg2, arg3);
}

export function IndexStart(arg1) {
  return window['go']['bridge']['App']['IndexStart'](arg1);
}

export function ListWorkspaceDir(arg1) {
  return window['go']['bridge']['App']['ListWorkspaceDir'](arg1);
}

export function LoadConversation(arg1) {
  return window['go']['bridge']['App']['LoadConversation'](arg1);
}

export function NewConversation() {
  return window['go']['bridge']['App']['NewConversation']();
}

export function OpenFileInUI(arg1) {
  return window['go']['bridge']['App']['OpenFileInUI'](arg1);
}

export function OpenProjectDataDir() {
  return window['go']['bridge']['App']['OpenProjectDataDir']();
}

export function PromptApproval(arg1, arg2, arg3) {
  return window['go']['bridge']['App']['PromptApproval'](arg1, arg2, arg3);
}

export function PromptChoice(arg1, arg2, arg3) {
  return window['go']['bridge']['App']['PromptChoice'](arg1, arg2, arg3);
}

export function ReadWorkspaceFile(arg1) {
  return window['go']['bridge']['App']['ReadWorkspaceFile'](arg1);
}

export function ReindexSymbols() {
  return window['go']['bridge']['App']['ReindexSymbols']();
}

export function ReloadMCP() {
  return window['go']['bridge']['App']['ReloadMCP']();
}

export function ResetGlobalUsage() {
  return window['go']['bridge']['App']['ResetGlobalUsage']();
}

export function ResetUsage() {
  return window['go']['bridge']['App']['ResetUsage']();
}

export function ResolveChoice(arg1, arg2) {
  return window['go']['bridge']['App']['ResolveChoice'](arg1, arg2);
}

export function RunProfiler() {
  return window['go']['bridge']['App']['RunProfiler']();
}

export function RunQuickProfiler() {
  return window['go']['bridge']['App']['RunQuickProfiler']();
}

export function SaveRules(arg1) {
  return window['go']['bridge']['App']['SaveRules'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['bridge']['App']['SaveSettings'](arg1);
}

export function SaveUILayout(arg1) {
  return window['go']['bridge']['App']['SaveUILayout'](arg1);
}

export function SearchCode(arg1, arg2, arg3) {
  return window['go']['bridge']['App']['SearchCode'](arg1, arg2, arg3);
}

export function SendChat(arg1, arg2) {
  return window['go']['bridge']['App']['SendChat'](arg1, arg2);
}

export function SendUserMessage(arg1) {
  return window['go']['bridge']['App']['SendUserMessage'](arg1);
}

export function SetAttachments(arg1) {
  return window['go']['bridge']['App']['SetAttachments'](arg1);
}

export function SetBusy(arg1) {
  return window['go']['bridge']['App']['SetBusy'](arg1);
}

export function SetModel(arg1) {
  return window['go']['bridge']['App']['SetModel'](arg1);
}

export function SetWorkspace(arg1) {
  return window['go']['bridge']['App']['SetWorkspace'](arg1);
}

export function ShouldRunProfiler() {
  return window['go']['bridge']['App']['ShouldRunProfiler']();
}

export function StopLLM() {
  return window['go']['bridge']['App']['StopLLM']();
}

export function UpdateEditorContext(arg1, arg2, arg3) {
  return window['go']['bridge']['App']['UpdateEditorContext'](arg1, arg2, arg3);
}

export function WithConfig(arg1) {
  return window['go']['bridge']['App']['WithConfig'](arg1);
}

export function WithContext(arg1) {
  return window['go']['bridge']['App']['WithContext'](arg1);
}

export function WithEngine(arg1) {
  return window['go']['bridge']['App']['WithEngine'](arg1);
}

export function WithMemoryStore(arg1) {
  return window['go']['bridge']['App']['WithMemoryStore'](arg1);
}

export function WithSettings(arg1) {
  return window['go']['bridge']['App']['WithSettings'](arg1);
}

export function WithTools(arg1) {
  return window['go']['bridge']['App']['WithTools'](arg1);
}

export function WriteWorkspaceFile(arg1) {
  return window['go']['bridge']['App']['WriteWorkspaceFile'](arg1);
}
