name: Format & Vet

on:
  pull_request:
    branches: [ main ]

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - name: go vet
        run: go vet ./...
      - name: gofmt -s check
        run: |
          files=$(gofmt -l -s .)
          if [ -n "$files" ]; then
            echo "Files need gofmt -s:"
            echo "$files"
            exit 1
          fi
